# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/SDverisure/Documents/4 TELECO/DSED/Punto_1_test_ok/Punto_1_test_ok/Punto_1_test_ok.cache/wt} [current_project]
set_property parent.project_path {C:/Users/SDverisure/Documents/4 TELECO/DSED/Punto_1_test_ok/Punto_1_test_ok/Punto_1_test_ok.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/SDverisure/Documents/4 TELECO/DSED/Punto_1_test_ok/Punto_1_test_ok/Punto_1_test_ok.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/SDverisure/Documents/4 TELECO/DSED/Punto_1_test_ok/Punto_1_test_ok/Punto_1_test_ok.srcs/sources_1/imports/new/gen_enables.vhd}
  {C:/Users/SDverisure/Documents/4 TELECO/DSED/Punto_1_test_ok/Punto_1_test_ok/Punto_1_test_ok.srcs/sources_1/imports/new/packageDSED.vhd}
  {C:/Users/SDverisure/Documents/4 TELECO/DSED/Punto_1_test_ok/Punto_1_test_ok/Punto_1_test_ok.srcs/sources_1/imports/new/inputMicrophone.vhd}
  {C:/Users/SDverisure/Documents/4 TELECO/DSED/Punto_1_test_ok/Punto_1_test_ok/Punto_1_test_ok.srcs/sources_1/new/outputMicrophone.vhd}
  {C:/Users/SDverisure/Documents/4 TELECO/DSED/Punto_1_test_ok/Punto_1_test_ok/Punto_1_test_ok.srcs/sources_1/new/audioInterface.vhd}
  {C:/Users/SDverisure/Documents/4 TELECO/DSED/Punto_1_test_ok/Punto_1_test_ok/Punto_1_test_ok.srcs/sources_1/new/simpleAudioSystem.vhd}
}
read_ip -quiet {{c:/Users/SDverisure/Documents/4 TELECO/DSED/Punto_1_test_ok/Punto_1_test_ok/Punto_1_test_ok.srcs/sources_1/ip/clk_12Mhz/clk_12Mhz.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/SDverisure/Documents/4 TELECO/DSED/Punto_1_test_ok/Punto_1_test_ok/Punto_1_test_ok.srcs/sources_1/ip/clk_12Mhz/clk_12Mhz_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/SDverisure/Documents/4 TELECO/DSED/Punto_1_test_ok/Punto_1_test_ok/Punto_1_test_ok.srcs/sources_1/ip/clk_12Mhz/clk_12Mhz.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/SDverisure/Documents/4 TELECO/DSED/Punto_1_test_ok/Punto_1_test_ok/Punto_1_test_ok.srcs/sources_1/ip/clk_12Mhz/clk_12Mhz_ooc.xdc}}]
set_property is_locked true [get_files {{c:/Users/SDverisure/Documents/4 TELECO/DSED/Punto_1_test_ok/Punto_1_test_ok/Punto_1_test_ok.srcs/sources_1/ip/clk_12Mhz/clk_12Mhz.xci}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/SDverisure/Documents/4 TELECO/DSED/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/SDverisure/Documents/4 TELECO/DSED/Nexys4DDR_Master.xdc}}]


synth_design -top simpleAudioSystem -part xc7a100tcsg324-1


write_checkpoint -force -noxdef simpleAudioSystem.dcp

catch { report_utilization -file simpleAudioSystem_utilization_synth.rpt -pb simpleAudioSystem_utilization_synth.pb }
